branches:
  - main
  - name: alpha
    prerelease: true
repositoryUrl: https://github.com/oplik0/solo2-gui.git
plugins:
  - ["@semantic-release/commit-analyzer", { preset: "conventionalcommits" }]
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/changelog", { changelogFile: "docs/CHANGELOG.md" }]
  - ["@semantic-release/npm", { npmPublish: false }]
  - [
      "@semantic-release/git",
      { assets: ["docs/CHANGELOG.md", "package.json", "src-tauri/Cargo.toml"] },
    ]
  - ["@opliko/semantic-release-github", { draftRelease: true }]
  - [
      "@semantic-release/exec",
      {
        verifyReleaseCmd: 'sed -i -z ''s/name = "solo2-desktop"\nversion = "${lastRelease.version}"/name = "solo2-desktop"\nversion = "${nextRelease.version}"/g'' src-tauri/Cargo.toml src-tauri/Cargo.lock',
        successCmd: "node .github/workflows/output-release-id.js ${releases.filter(r => r.pluginName === '@opliko/semantic-release-github')[0].id}",
      },
    ]
