branches:
  - main
  - name: alpha
    prerelease: true
repositoryUrl: https://github.com/oplik0/solo2-gui.git
plugins:
  - ["@semantic-release/commit-analyzer", { preset: "conventionalcommits" }]
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/changelog", { changelogFile: "docs/CHANGELOG.md" }]
  - ["@semantic-release/npm", { npmPublish: false }]
  - ["@semantic-release/git", { assets: ["docs/CHANGELOG.md", "package.json"] }]
  - ["@opliko/semantic-release-github", { draftRelease: true }]
  - [
      "@semantic-release/exec",
      {
        "successCmd": "node .github/workflows/output-release-id.js ${releases[0].id}",
      },
    ]
